Dev
AlexFoxalt/HomeworksPart2 pull request #8
Opened 2021-10-04 11:09 UTC by AlexFoxalt

HW10 Done

2021-10-04 18:22 UTC, dbradul requested changes

2021-10-04 18:22 UTC, dbradul commented on HW10/users/views.py
> +        )
Для наложения множественных уловий OR можно использовать такую идиому:
```
fields = ['name', 'city', 'email', 'faculty', 'previous_educational_institution']

students = Student.objects.none()  # <-- начинаем с пустого QS и постепенно его расширяем с помощью OR
or_cond = Q()

for field in fields:
    or_cond |= Q(**{f'{field}__contains': text})

students = students.filter(or_cond)

```

2021-10-04 18:22 UTC, dbradul commented on HW10/users/models.py
> +            cls.objects.create(**data)
Можно вынести общую часть в базовый класс, используя classmethod:
```
class User:
    ...
    @classmethod
    def generate_entity(cls, count):
        for iteration in range(count):
            data = {
                    'name': f.name(),
                    'city': f.city(),
                    'email': f.email(),
                    'faculty': mine_faker_of_faculties()
                }
        cls._extend_fields(data)
        cls.objects.create(**data)


class Teacher(User):
    @classmethod
    def _extend_fields(cls, data):
        data.update({
            'birthday': f.date_between(start_date='-70y', end_date='-25y'),
            'position': 'Teacher',
            'date_of_employment': f.date_between(start_date='-30y', end_date='today'),
            'experience_in_years': randint(1, 30)
        })

class Student(User):
    @classmethod
    def _extend_fields(cls, data):
        data.update({
            'birthday': f.date_between(start_date='-50y', end_date='-16y'),
            'position': 'Student',
            'previous_educational_institution': f'School №{randint(1, 100)}'
        })

```

2021-10-05 09:23 UTC, AlexFoxalt commented on HW10/users/views.py
> +        return HttpResponseBadRequest(request, err)
Сделано, работает

2021-10-05 09:23 UTC, AlexFoxalt commented on HW10/users/models.py
> +        return ' --- '.join(field_values)
Не работает, ошибка уходит в рекурсию

2021-10-05 09:42 UTC, AlexFoxalt commented on HW10/users/views.py
> +        applied_filters.append(f'experience_in_years ~ "{experience_in_years}"')
Сделано, работает

2021-10-05 10:00 UTC, AlexFoxalt commented on HW10/users/views.py
> +        )
Для корректной работы требуется: students = Student.objects.all() вместо .none()
Сделано, работает

2021-10-05 10:03 UTC, AlexFoxalt commented on HW10/users/models.py
> +            cls.objects.create(**data)
Очень круто! Сделано, работает

2021-10-05 10:06 UTC, merged