Dev
AlexFoxalt/HomeworksPart2 pull request #9
Opened 2021-10-09 13:09 UTC by AlexFoxalt

HW11 Done

2021-10-09 20:01 UTC, dbradul requested changes

2021-10-10 06:32 UTC, AlexFoxalt commented on DJsite/users/models.py
> +        for repeat in range(count):
Сделано

2021-10-10 06:34 UTC, AlexFoxalt commented on DJsite/users/views.py
> +        if position == 'Student':
Не сделано, не будет работать в текущем месте, так как требуется

2021-10-10 06:35 UTC, AlexFoxalt commented on DJsite/users/forms.py
> +        invalid_domain_names = ('@abc.com', '@123.com', '@xyz.com')
Сделано

2021-10-10 06:35 UTC, merged